[package]
name = "minparser"
version = "0.10.0"
description = "Simple parsing functions"
edition = "2024"
license = "GPL-3.0-or-later"
keywords = ["parser", "scanner"]
categories = ["no-std", "parsing"]
homepage = "https://github.com/Loara-crates/minparser"
repository = "https://github.com/Loara-crates/minparser"
readme = "README.md"

[features]
alloc = []
nightly-features = []
std = ["alloc"]

[dependencies]
thiserror = { version = "2.0.14", default-features = false }

[package.metadata.docs.rs]
all-features = true
